# projects.toml file describing inputs for dream2nix
#
# To re-generate this file, run:
#   nix run .#detect-projects $source
# ... where `$source` points to the source of your project.
#
# If the local flake is unavailable, alternatively execute the app from the
# upstream dream2nix flake:
#   nix run github:nix-community/dream2nix#detect-projects $source

[wipeclean]
name = "wipeclean"
relPath = ""
subsystem = "nodejs"
translator = "package-lock"
translators = [ "package-lock", "package-json",]

[wipeclean.subsystemInfo]
